[package]
edition = "2021"
name    = "lqdc-common"
version = "0.1.0"

[dependencies]
lang_pt.workspace   = true
miette.workspace    = true
thiserror.workspace = true

frontend = { path = "../frontend" }
