[package]
edition = "2021"
name    = "frontend"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegem.workspace   = true
miette.workspace    = true
thiserror.workspace = true

nom = { version = "7.1" }
